# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

int_anyNA <- function(x) {
    .Call(`_detrendr_int_anyNA`, x)
}

dbl_anyNA <- function(x) {
    .Call(`_detrendr_dbl_anyNA`, x)
}

brightness_cols <- function(cols) {
    .Call(`_detrendr_brightness_cols`, cols)
}

brightness_cols_given_mean <- function(cols, means) {
    .Call(`_detrendr_brightness_cols_given_mean`, cols, means)
}

var_cols_given_mean <- function(cols, means) {
    .Call(`_detrendr_var_cols_given_mean`, cols, means)
}

mean_frames_ <- function(arr3d) {
    .Call(`_detrendr_mean_frames_`, arr3d)
}

sum_frames_ <- function(arr3d) {
    .Call(`_detrendr_sum_frames_`, arr3d)
}

int_sum_frames_na_omit <- function(arr3d) {
    .Call(`_detrendr_int_sum_frames_na_omit`, arr3d)
}

dbl_sum_frames_na_omit <- function(arr3d) {
    .Call(`_detrendr_dbl_sum_frames_na_omit`, arr3d)
}

int_mean_frames_na_omit <- function(arr3d) {
    .Call(`_detrendr_int_mean_frames_na_omit`, arr3d)
}

dbl_mean_frames_na_omit <- function(arr3d) {
    .Call(`_detrendr_dbl_mean_frames_na_omit`, arr3d)
}

sum_pillars_ <- function(arr3d) {
    .Call(`_detrendr_sum_pillars_`, arr3d)
}

mean_pillars_ <- function(arr3d) {
    .Call(`_detrendr_mean_pillars_`, arr3d)
}

var_pillars_ <- function(arr3d) {
    .Call(`_detrendr_var_pillars_`, arr3d)
}

median_pillars_ <- function(arr3d) {
    .Call(`_detrendr_median_pillars_`, arr3d)
}

brightness_pillars_ <- function(arr3d) {
    .Call(`_detrendr_brightness_pillars_`, arr3d)
}

pillars_to_cols <- function(arr3d) {
    .Call(`_detrendr_pillars_to_cols`, arr3d)
}

cols_to_pillars <- function(mat, output_dim) {
    .Call(`_detrendr_cols_to_pillars`, mat, output_dim)
}

myrbernoulli_ <- function(p, seed) {
    .Call(`_detrendr_myrbernoulli_`, p, seed)
}

rfromboxes_ <- function(n, balls, weights, seed, quick) {
    .Call(`_detrendr_rfromboxes_`, n, balls, weights, seed, quick)
}

rtoboxes_ <- function(n, boxes, weights, capacities, seed, quick) {
    .Call(`_detrendr_rtoboxes_`, n, boxes, weights, capacities, seed, quick)
}

px_take_arr3d <- function(arr3d, frames_losing, seed) {
    .Call(`_detrendr_px_take_arr3d`, arr3d, frames_losing, seed)
}

px_take_mat <- function(mat, mat_orig, frames_losing, seed) {
    .Call(`_detrendr_px_take_mat`, mat, mat_orig, frames_losing, seed)
}

brightness_rows <- function(rows) {
    .Call(`_detrendr_brightness_rows`, rows)
}

brightness_rows_given_mean <- function(rows, means) {
    .Call(`_detrendr_brightness_rows_given_mean`, rows, means)
}

var_rows_given_mean <- function(rows, means) {
    .Call(`_detrendr_var_rows_given_mean`, rows, means)
}

sum_rows <- function(rows) {
    .Call(`_detrendr_sum_rows`, rows)
}

myrpois_ <- function(means, seed) {
    .Call(`_detrendr_myrpois_`, means, seed)
}

myrpois_frames_ <- function(means, frame_length, seed) {
    .Call(`_detrendr_myrpois_frames_`, means, frame_length, seed)
}

myrpois_frames_t_ <- function(means, frame_length, seed) {
    .Call(`_detrendr_myrpois_frames_t_`, means, frame_length, seed)
}

boxcar_smooth <- function(vec, l) {
    .Call(`_detrendr_boxcar_smooth`, vec, l)
}

weighted_smooth <- function(vec, weights) {
    .Call(`_detrendr_weighted_smooth`, vec, weights)
}

exp_smooth <- function(vec, tau, l) {
    .Call(`_detrendr_exp_smooth`, vec, tau, l)
}

boxcar_smooth_rows <- function(mat, l) {
    .Call(`_detrendr_boxcar_smooth_rows`, mat, l)
}

boxcar_smooth_pillars <- function(arr, l) {
    .Call(`_detrendr_boxcar_smooth_pillars`, arr, l)
}

exp_smooth_rows <- function(mat, tau, l) {
    .Call(`_detrendr_exp_smooth_rows`, mat, tau, l)
}

exp_smooth_pillars <- function(arr, tau, l) {
    .Call(`_detrendr_exp_smooth_pillars`, arr, tau, l)
}

square_root_ <- function(x) {
    .Call(`_detrendr_square_root_`, x)
}

mat_add1s <- function(mat, add_pos) {
    .Call(`_detrendr_mat_add1s`, mat, add_pos)
}

vec_add1s <- function(vec, add_pos) {
    .Call(`_detrendr_vec_add1s`, vec, add_pos)
}

