# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mean_frames <- function(arr3d) {
    .Call('_detrendr_mean_frames', PACKAGE = 'detrendr', arr3d)
}

med_reflect_extend_rows_ <- function(current, original, extend_both_sides_by, preserve_mean, smooth) {
    .Call('_detrendr_med_reflect_extend_rows_', PACKAGE = 'detrendr', current, original, extend_both_sides_by, preserve_mean, smooth)
}

med_reflect_extend_pillars_ <- function(current, original, extend_both_sides_by, preserve_mean = FALSE, smooth = FALSE) {
    .Call('_detrendr_med_reflect_extend_pillars_', PACKAGE = 'detrendr', current, original, extend_both_sides_by, preserve_mean, smooth)
}

mean_pillars_ <- function(arr3d) {
    .Call('_detrendr_mean_pillars_', PACKAGE = 'detrendr', arr3d)
}

var_pillars_ <- function(arr3d) {
    .Call('_detrendr_var_pillars_', PACKAGE = 'detrendr', arr3d)
}

median_pillars_ <- function(arr3d) {
    .Call('_detrendr_median_pillars_', PACKAGE = 'detrendr', arr3d)
}

myrbernoulli_ <- function(p, seed) {
    .Call('_detrendr_myrbernoulli_', PACKAGE = 'detrendr', p, seed)
}

brightness_rows_ <- function(rows) {
    .Call('_detrendr_brightness_rows_', PACKAGE = 'detrendr', rows)
}

mean_rows_ <- function(rows) {
    .Call('_detrendr_mean_rows_', PACKAGE = 'detrendr', rows)
}

myrpois_ <- function(means, seed) {
    .Call('_detrendr_myrpois_', PACKAGE = 'detrendr', means, seed)
}

myrpois_frames_ <- function(means, frame_length, seed) {
    .Call('_detrendr_myrpois_frames_', PACKAGE = 'detrendr', means, frame_length, seed)
}

boxcar_smooth <- function(extended, extended_both_sides_by, l) {
    .Call('_detrendr_boxcar_smooth', PACKAGE = 'detrendr', extended, extended_both_sides_by, l)
}

weighted_smooth <- function(extended, extended_both_sides_by, weights, weight_sum) {
    .Call('_detrendr_weighted_smooth', PACKAGE = 'detrendr', extended, extended_both_sides_by, weights, weight_sum)
}

exp_smooth <- function(extended, extended_both_sides_by, tau, l) {
    .Call('_detrendr_exp_smooth', PACKAGE = 'detrendr', extended, extended_both_sides_by, tau, l)
}

boxcar_smooth_rows_ <- function(extended, extended_both_sides_by, l) {
    .Call('_detrendr_boxcar_smooth_rows_', PACKAGE = 'detrendr', extended, extended_both_sides_by, l)
}

boxcar_smooth_pillars_ <- function(extended, extended_both_sides_by, l) {
    .Call('_detrendr_boxcar_smooth_pillars_', PACKAGE = 'detrendr', extended, extended_both_sides_by, l)
}

exp_smooth_rows_ <- function(extended, extended_both_sides_by, tau, l) {
    .Call('_detrendr_exp_smooth_rows_', PACKAGE = 'detrendr', extended, extended_both_sides_by, tau, l)
}

exp_smooth_pillars_ <- function(extended, extended_both_sides_by, tau, l) {
    .Call('_detrendr_exp_smooth_pillars_', PACKAGE = 'detrendr', extended, extended_both_sides_by, tau, l)
}

square_root_ <- function(x) {
    .Call('_detrendr_square_root_', PACKAGE = 'detrendr', x)
}

